In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.options.display.max_columns = None
df = pd.read_csv('./prosperCleanedData.csv')
df.head()

,ListingCreationDate,CreditGrade,Term,ClosedDate,BorrowerAPR,BorrowerRate,ProsperRating (numeric),ProsperRating (Alpha),ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,DateCreditPulled,CreditScoreRangeLower,CurrentCreditLines,TotalCreditLinespast7years,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,BankcardUtilization,AvailableBankcardCredit,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanCurrentDaysDelinquent,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,Investors,IsDefaulted,LoanOriginationYear,LoanOriginationMonth,LoanOriginationDay,ClosedDateYear,ClosedDateMonth,ClosedDateDay,ListingCreationYear,ListingCreationMonth,ListingCreationDay,DateCreditPulledYear,DateCreditPulledMonth,DateCreditPulledDay,LoanOriginationQuarterYear,LoanOriginationQuarterMonth,LoanOriginationQuarterDay
0,2007-08-26 19:09:29.263,C,36,2009-08-14,0.16516,0.1580,4.0,Missing,0,CO,Other,Self-employed,2.0,True,True,2007-08-26 18:41:46.780,640.0,5.0,12.0,3.0,3.0,2.0,4.0,0.0,0.0,0.00,1500.0,0.81,0.0,0.17,"$25,000-49,999",True,3083.333333,0,78,9425,2007-09-12,2007-07-01,330.43,11396.14,9425.00,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,258,0,2007,9,12,2009,8,14,2007,8,26,2007,8,26,2007,7,1
1,2014-02-27 08:28:07.900,Missing,36,2014-03-03,0.12016,0.0920,6.0,A,2,CO,Professional,Employed,44.0,False,False,2014-02-27 08:28:14.000,680.0,14.0,29.0,3.0,5.0,0.0,0.0,1.0,0.0,0.21,10266.0,1.00,2.0,0.18,"$50,000-74,999",True,6125.000000,0,0,10000,2014-03-03,2014-01-01,318.93,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0,0,1,0,2014,3,3,2014,3,3,2014,2,27,2014,2,27,2014,1,1
2,2007-01-05 15:00:47.090,HR,36,2009-12-17,0.28269,0.2750,4.0,Missing,0,GA,Other,Not available,67.0,False,True,2007-01-02 14:09:10.060,480.0,10.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,0.60,4100.0,0.94,0.0,0.06,Not displayed,True,2083.333333,0,86,3001,2007-01-17,2007-01-01,123.32,4186.63,3001.00,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,41,0,2007,1,17,2009,12,17,2007,1,5,2007,1,2,2007,1,1
3,2012-10-22 11:02:35.010,Missing,36,2012-11-01,0.12528,0.0974,6.0,A,16,GA,Skilled Labor,Employed,113.0,True,False,2012-10-22 11:02:32.000,800.0,5.0,29.0,0.0,1.0,4.0,14.0,0.0,0.0,0.04,30754.0,0.76,0.0,0.15,"$25,000-49,999",True,2875.000000,0,16,10000,2012-11-01,2012-10-01,321.45,5143.20,4091.09,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,158,0,2012,11,1,2012,11,1,2012,10,22,2012,10,22,2012,10,1
4,2013-09-14 18:38:39.097,Missing,36,2013-09-20,0.24614,0.2085,3.0,D,2,MN,Executive,Employed,44.0,True,False,2013-09-14 18:38:44.000,680.0,19.0,49.0,1.0,9.0,0.0,0.0,0.0,0.0,0.81,695.0,0.95,2.0,0.26,"$100,000+",True,9583.333333,0,6,15000,2013-09-20,2013-07-01,563.97,2819.85,1563.22,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,20,0,2013,9,20,2013,9,20,2013,9,14,2013,9,14,2013,7,1

In [3]:
df.shape

(113937, 66)

In [4]:
df.columns

Index(['ListingCreationDate', 'CreditGrade', 'Term', 'ClosedDate',
       'BorrowerAPR', 'BorrowerRate', 'ProsperRating (numeric)',
       'ProsperRating (Alpha)', 'ListingCategory (numeric)', 'BorrowerState',
       'Occupation', 'EmploymentStatus', 'EmploymentStatusDuration',
       'IsBorrowerHomeowner', 'CurrentlyInGroup', 'DateCreditPulled',
       'CreditScoreRangeLower', 'CurrentCreditLines',
       'TotalCreditLinespast7years', 'InquiriesLast6Months', 'TotalInquiries',
       'CurrentDelinquencies', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'BankcardUtilization', 'AvailableBankcardCredit',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'DebtToIncomeRatio', 'IncomeRange', 'IncomeVerifiable',
       'StatedMonthlyIncome', 'LoanCurrentDaysDelinquent',
       'LoanMonthsSinceOrigination', 'LoanOriginalAmount',
       'LoanOriginationDate', 'LoanOriginationQuarter', 'MonthlyLoanPayment',
       'LP_CustomerPayments', 'LP_CustomerPrincipalPayments', 'LP_ServiceFees',
       'LP_CollectionFees', 'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'Investors', 'IsDefaulted',
       'LoanOriginationYear', 'LoanOriginationMonth', 'LoanOriginationDay',
       'ClosedDateYear', 'ClosedDateMonth', 'ClosedDateDay',
       'ListingCreationYear', 'ListingCreationMonth', 'ListingCreationDay',
       'DateCreditPulledYear', 'DateCreditPulledMonth', 'DateCreditPulledDay',
       'LoanOriginationQuarterYear', 'LoanOriginationQuarterMonth',
       'LoanOriginationQuarterDay'],
      dtype='object')

In [5]:
df['EmploymentStatusDuration'].value_counts()

EmploymentStatusDuration
67.0     8173
0.0      1534
4.0      1186
1.0      1177
3.0      1174
         ...
731.0       1
574.0       1
525.0       1
581.0       1
578.0       1
Name: count, Length: 605, dtype: int64

In [6]:
for col in df.columns:
    print(df[col].value_counts())

ListingCreationDate
2013-10-02 17:20:16.550    6
2013-08-28 20:31:41.107    4
2013-12-06 11:44:58.283    4
2013-12-06 05:43:13.830    4
2013-09-08 09:27:44.853    4
                          ..
2012-11-08 20:07:36.600    1
2013-11-23 04:52:50.057    1
2008-06-19 12:02:53.300    1
2013-05-07 18:49:59.750    1
2013-12-03 11:34:46.127    1
Name: count, Length: 113064, dtype: int64
CreditGrade
Missing    84984
C           5649
D           5153
B           4389
AA          3509
HR          3508
A           3315
E           3289
NC           141
Name: count, dtype: int64
Term
36    87778
60    24545
12     1614
Name: count, dtype: int64
ClosedDate
2014-01-22    552
2014-02-19    539
2013-11-13    522
2013-10-16    484
2014-01-28    401
             ...
2006-07-18      1
2006-07-05      1
2006-10-29      1
2006-11-04      1
2005-11-25      1
Name: count, Length: 2787, dtype: int64
BorrowerAPR
0.35797    3672
0.35643    1644
0.37453    1260
0.30532     902
0.29510     747
           ...
0.05104       1
0.11145       1
0.21402       1
0.23631       1
0.20582       1
Name: count, Length: 6677, dtype: int64
BorrowerRate
0.3177    3672
0.3500    1905
0.3199    1651
0.2900    1508
0.2699    1319
          ...
0.2773       1
0.1641       1
0.1263       1
0.1406       1
0.0857       1
Name: count, Length: 2294, dtype: int64
ProsperRating (numeric)
4.0    47429
5.0    15581
6.0    14551
3.0    14274
2.0     9795
1.0     6935
7.0     5372
Name: count, dtype: int64
ProsperRating (Alpha)
Missing    29084
C          18345
B          15581
A          14551
D          14274
E           9795
HR          6935
AA          5372
Name: count, dtype: int64
ListingCategory (numeric)
1     58308
0     16965
7     10494
2      7433
3      7189
6      2572
4      2395
13     1996
15     1522
18      885
14      876
20      771
19      768
5       756
16      304
11      217
8       199
10       91
9        85
12       59
17       52
Name: count, dtype: int64
BorrowerState
CA         14717
TX          6842
NY          6729
FL          6720
IL          5921
Missing     5515
GA          5008
OH          4197
MI          3593
VA          3278
NJ          3097
NC          3084
WA          3048
PA          2972
MD          2821
MO          2615
MN          2318
MA          2242
CO          2210
IN          2078
AZ          1901
WI          1842
OR          1817
TN          1737
AL          1679
CT          1627
SC          1122
NV          1090
KS          1062
KY           983
OK           971
LA           954
UT           877
AR           855
MS           787
NE           674
ID           599
NH           551
NM           472
RI           435
HI           409
WV           391
DC           382
MT           330
DE           300
VT           207
AK           200
SD           189
IA           186
WY           150
ME           101
ND            52
Name: count, dtype: int64
Occupation
Other                          28617
Professional                   13628
Computer Programmer             4478
Executive                       4311
Teacher                         3759
                               ...
Dentist                           68
Student - College Freshman        41
Student - Community College       28
Judge                             22
Student - Technical School        16
Name: count, Length: 68, dtype: int64
EmploymentStatus
Employed         67322
Full-time        26355
Self-employed     6134
Not available     5347
Other             3806
Missing           2255
Part-time         1088
Not employed       835
Retired            795
Name: count, dtype: int64
EmploymentStatusDuration
67.0     8173
0.0      1534
4.0      1186
1.0      1177
3.0      1174
         ...
731.0       1
574.0       1
525.0       1
581.0       1
578.0       1
Name: count, Length: 605, dtype: int64
IsBorrowerHomeowner
True     57478
False    56459
Name: count, dtype: int64
CurrentlyInGroup
False    101218
True      12719
Name: count, dtype: int64
DateCreditPulled
2013-12-23 09:38:12.000    6
2014-02-09 12:14:41.000    4
2014-01-14 20:17:49.000    4
2013-12-06 05:43:16.000    4
2013-11-21 09:09:41.000    4
                          ..
2012-10-27 21:31:23.000    1
2013-11-23 04:52:52.000    1
2008-06-19 10:02:10.457    1
2013-05-07 18:49:57.000    1
2013-06-11 05:49:29.000    1
Name: count, Length: 112992, dtype: int64
CreditScoreRangeLower
680.0    17083
660.0    16366
700.0    15471
720.0    12923
640.0    12199
740.0     9267
760.0     6606
780.0     4624
620.0     4172
600.0     3602
800.0     2644
520.0     1593
540.0     1474
820.0     1409
560.0     1357
580.0     1125
840.0      567
500.0      554
480.0      346
860.0      212
460.0      141
0.0        133
440.0       36
880.0       27
420.0        5
360.0        1
Name: count, dtype: int64
CurrentCreditLines
10.0    15756
8.0      8985
7.0      8945
9.0      8731
11.0     7500
6.0      7449
12.0     6530
5.0      6367
13.0     5677
14.0     4927
4.0      4804
15.0     3985
3.0      3553
16.0     3468
17.0     2619
2.0      2467
18.0     2242
19.0     1730
20.0     1377
1.0      1351
21.0     1068
22.0      828
23.0      670
24.0      563
25.0      446
0.0       385
26.0      348
27.0      251
28.0      205
29.0      145
30.0      119
31.0       91
32.0       75
33.0       62
35.0       40
34.0       39
36.0       34
38.0       23
37.0       23
39.0       13
40.0       10
41.0        8
44.0        4
42.0        3
48.0        3
54.0        3
52.0        3
45.0        3
47.0        3
56.0        2
43.0        1
59.0        1
51.0        1
46.0        1
Name: count, dtype: int64
TotalCreditLinespast7years
25.0     4144
21.0     3552
22.0     3507
20.0     3480
19.0     3451
         ...
125.0       1
136.0       1
117.0       1
100.0       1
120.0       1
Name: count, Length: 118, dtype: int64
InquiriesLast6Months
0.0      50005
1.0      29318
2.0      14432
3.0       7697
4.0       4297
5.0       2610
6.0       1664
7.0       1014
8.0        696
9.0        508
10.0       372
11.0       275
12.0       207
13.0       163
14.0       128
15.0        98
16.0        79
17.0        64
18.0        53
21.0        40
19.0        33
20.0        30
22.0        22
23.0        18
24.0        16
26.0        14
25.0        14
31.0        10
27.0         8
28.0         8
29.0         6
32.0         4
35.0         4
30.0         4
34.0         4
40.0         3
37.0         3
44.0         2
33.0         2
38.0         2
42.0         1
41.0         1
36.0         1
63.0         1
97.0         1
46.0         1
52.0         1
105.0        1
53.0         1
50.0         1
Name: count, dtype: int64
TotalInquiries
2.0      14887
3.0      13934
1.0      13785
4.0      13307
5.0      10098
         ...
75.0         1
377.0        1
95.0         1
88.0         1
158.0        1
Name: count, Length: 102, dtype: int64
CurrentDelinquencies
0.0     90439
1.0     11716
2.0      4357
3.0      2098
4.0      1379
5.0       916
6.0       690
7.0       517
8.0       397
9.0       289
10.0      212
11.0      191
12.0      147
13.0      111
15.0       83
14.0       71
16.0       58
17.0       40
18.0       37
21.0       31
19.0       28
20.0       27
22.0       21
27.0       12
24.0       12
23.0        9
26.0        8
31.0        6
25.0        5
32.0        5
28.0        5
35.0        2
41.0        2
30.0        2
36.0        2
33.0        1
64.0        1
50.0        1
59.0        1
57.0        1
39.0        1
45.0        1
83.0        1
82.0        1
37.0        1
40.0        1
51.0        1
Name: count, dtype: int64
DelinquenciesLast7Years
0.0     77429
1.0      3967
3.0      3183
2.0      2879
4.0      2592
        ...
81.0        4
94.0        3
85.0        3
98.0        3
93.0        2
Name: count, Length: 100, dtype: int64
PublicRecordsLast10Years
0.0     86500
1.0     22834
2.0      3011
3.0       894
4.0       345
5.0       151
6.0        70
7.0        46
8.0        31
9.0        15
10.0        8
11.0        7
16.0        5
14.0        4
12.0        4
15.0        3
21.0        1
25.0        1
13.0        1
38.0        1
30.0        1
20.0        1
34.0        1
22.0        1
17.0        1
Name: count, dtype: int64
PublicRecordsLast12Months
0.0     112545
1.0       1255
2.0         96
3.0         28
4.0         10
7.0          2
20.0         1
Name: count, dtype: int64
BankcardUtilization
0.60    8678
0.00    6782
0.98    2171
0.97    2053
0.96    1798
        ...
2.21       1
1.96       1
1.84       1
1.64       1
1.72       1
Name: count, Length: 201, dtype: int64
AvailableBankcardCredit
4100.0     7554
0.0        4881
500.0       303
300.0       151
1000.0      145
           ...
17923.0       1
24283.0       1
8687.0        1
11306.0       1
25650.0       1
Name: count, Length: 31829, dtype: int64
TradesNeverDelinquent (percentage)
1.00    41705
0.94    10595
0.96     4245
0.95     3755
0.90     3171
        ...
0.32        5
0.06        3
0.99        1
0.03        1
0.49        1
Name: count, Length: 98, dtype: int64
TradesOpenedLast6Months
0.0     61793
1.0     31475
2.0     13180
3.0      4678
4.0      1646
5.0       652
6.0       273
7.0       116
8.0        54
9.0        24
10.0       13
11.0       12
12.0        8
13.0        5
17.0        2
15.0        2
14.0        2
16.0        1
20.0        1
Name: count, dtype: int64
DebtToIncomeRatio
0.22000    12241
0.18000     4132
0.17000     3616
0.14000     3553
0.20000     3481
           ...
3.29000        1
0.13213        1
0.08865        1
0.08335        1
4.00000        1
Name: count, Length: 1207, dtype: int64
IncomeRange
$25,000-49,999    32192
$50,000-74,999    31050
$100,000+         17337
$75,000-99,999    16916
Not displayed      7741
$1-24,999          7274
Not employed        806
$0                  621
Name: count, dtype: int64
IncomeVerifiable
True     105268
False      8669
Name: count, dtype: int64
StatedMonthlyIncome
4166.666667    3526
5000.000000    3389
3333.333333    2917
3750.000000    2428
5416.666667    2374
               ...
2861.000000       1
3903.166667       1
8074.916667       1
4424.000000       1
3814.250000       1
Name: count, Length: 13502, dtype: int64
LoanCurrentDaysDelinquent
0       94860
121       293
10        192
4          77
11         62
        ...
1040        1
1112        1
916         1
2349        1
1081        1
Name: count, Length: 2411, dtype: int64
LoanMonthsSinceOrigination
2      5865
3      5215
5      4899
1      4485
4      4336
       ...
56       20
100      13
58       13
99        9
98        8
Name: count, Length: 94, dtype: int64
LoanOriginalAmount
4000     14333
15000    12407
10000    11106
5000      6990
2000      6067
         ...
4916         1
31750        1
4190         1
2774         1
5364         1
Name: count, Length: 2468, dtype: int64
LoanOriginationDate
2014-01-22    491
2013-11-13    490
2014-02-19    439
2013-10-16    434
2014-01-28    339
             ...
2005-12-08      1
2005-11-23      1
2005-12-05      1
2005-11-29      1
2005-11-15      1
Name: count, Length: 1873, dtype: int64
LoanOriginationQuarter
2013-10-01    14450
2014-01-01    12172
2013-07-01     9180
2013-04-01     7099
2012-07-01     5632
2012-04-01     5061
2012-01-01     4435
2012-10-01     4425
2008-04-01     4344
2011-10-01     3913
2013-01-01     3616
2008-07-01     3602
2007-04-01     3118
2011-07-01     3093
2007-01-01     3079
2008-01-01     3074
2007-07-01     2671
2007-10-01     2592
2011-04-01     2478
2006-10-01     2403
2006-07-01     1934
2011-01-01     1744
2010-10-01     1600
2010-04-01     1539
2009-10-01     1449
2010-07-01     1270
2006-04-01     1254
2010-01-01     1243
2009-07-01      585
2008-10-01      532
2006-01-01      315
2005-10-01       22
2009-04-01       13
Name: count, dtype: int64
MonthlyLoanPayment
173.71     2423
0.00        935
172.76      536
86.85       472
174.20      460
           ...
243.73        1
1094.14       1
337.24        1
606.80        1
479.53        1
Name: count, Length: 23567, dtype: int64
LP_CustomerPayments
0.00        6208
2953.07      119
3126.78       83
3300.49       82
2779.36       82
            ...
4186.63        1
11396.14       1
3738.33        1
1929.41        1
29828.79       1
Name: count, Length: 78523, dtype: int64
LP_CustomerPrincipalPayments
0.00       6308
4000.00    2595
5000.00    2274
2000.00    2042
3000.00    1938
           ...
3987.33       1
4823.49       1
454.56        1
1028.04       1
3317.24       1
Name: count, Length: 49828, dtype: int64
LP_ServiceFees
 0.00      7164
-12.74      833
-8.49       746
-3.40       505
-16.99      304
           ...
-261.13       1
-260.75       1
-78.50        1
-253.83       1
-246.78       1
Name: count, Length: 19813, dtype: int64
LP_CollectionFees
 0.00      105771
-17.00         55
-8.50          54
-29.53         45
-34.00         43
            ...
-251.41         1
-155.10         1
-57.88          1
-549.86         1
-104.10         1
Name: count, Length: 6175, dtype: int64
LP_GrossPrincipalLoss
0.00       97034
4000.00       84
3000.00       50
1000.00       49
2000.00       45
           ...
1881.57        1
3969.04        1
6668.40        1
2887.47        1
8077.26        1
Name: count, Length: 15848, dtype: int64
LP_NetPrincipalLoss
0.00        97222
4000.00        80
3000.00        47
1000.00        45
5000.00        39
            ...
11992.05        1
1881.57         1
3969.03         1
6668.39         1
6820.28         1
Name: count, Length: 15709, dtype: int64
LP_NonPrincipalRecoverypayments
0.00       110676
100.00         59
50.00          44
25.00          31
85.00          28
            ...
49.54           1
1350.12         1
3598.21         1
1615.49         1
764.27          1
Name: count, Length: 2631, dtype: int64
PercentFunded
1.0000    113067
0.9998         5
0.7000         4
0.8087         4
0.7049         3
           ...
0.9006         1
0.7552         1
0.7880         1
0.7392         1
0.9768         1
Name: count, Length: 719, dtype: int64
Recommendations
0     109678
1       3516
2        568
3        108
4         26
5         14
9          6
7          5
6          4
8          3
16         2
18         2
39         1
14         1
21         1
24         1
19         1
Name: count, dtype: int64
InvestmentFromFriendsCount
0     111806
1       1835
2        215
3         40
4         15
5          8
9          5
6          4
8          3
7          2
15         1
20         1
33         1
13         1
Name: count, dtype: int64
Investors
1      27814
2       1386
3        991
4        827
5        753
       ...
894        1
870        1
735        1
912        1
754        1
Name: count, Length: 751, dtype: int64
IsDefaulted
0    96927
1    17010
Name: count, dtype: int64
LoanOriginationYear
2013    34345
2012    19553
2014    12172
2008    11552
2007    11460
2011    11228
2006     5906
2010     5652
2009     2047
2005       22
Name: count, dtype: int64
LoanOriginationMonth
1     11395
10    11043
12    10708
2      9728
11     9635
8      9592
9      9221
7      9154
6      8847
3      8555
5      8500
4      7559
Name: count, dtype: int64
LoanOriginationDay
30    4812
27    4548
28    4254
24    4154
29    4093
13    4090
26    4073
19    3949
23    3935
10    3907
20    3897
7     3863
25    3845
18    3834
6     3741
16    3731
22    3688
17    3681
11    3672
21    3636
15    3548
12    3434
5     3413
14    3371
8     3349
9     3304
4     3107
31    3092
3     3084
2     2621
1     2211
Name: count, dtype: int64
ClosedDateYear
2013    43583
2012    19132
2014    14854
2011    11066
2009     8197
2010     7633
2008     5703
2007     3363
2006      398
2005        8
Name: count, dtype: int64
ClosedDateMonth
1     12402
2     11552
12    11215
10    10981
11     9996
9      9027
8      8964
3      8936
7      8638
6      7948
5      7323
4      6955
Name: count, dtype: int64
ClosedDateDay
30    4385
27    4266
24    4097
19    4021
13    4018
10    3998
26    3928
18    3920
28    3899
7     3898
16    3854
6     3814
20    3780
23    3779
29    3774
11    3750
25    3736
17    3720
5     3651
22    3649
15    3601
4     3493
21    3484
9     3457
3     3450
12    3409
14    3355
8     3315
2     3010
31    2772
1     2654
Name: count, dtype: int64
ListingCreationYear
2013    35413
2012    19556
2007    11557
2011    11442
2008    11263
2014    10734
2006     6213
2010     5530
2009     2206
2005       23
Name: count, dtype: int64
ListingCreationMonth
1     11214
10    10539
12    10320
2     10124
9     10074
11     9952
7      9506
8      9202
6      8672
5      8641
3      8032
4      7661
Name: count, dtype: int64
ListingCreationDay
6     4037
17    4032
5     3965
16    3942
7     3928
4     3898
21    3881
3     3874
20    3841
9     3836
13    3827
15    3819
26    3802
22    3800
11    3784
12    3768
18    3766
10    3740
14    3702
23    3698
27    3694
19    3689
8     3649
24    3639
28    3632
2     3619
25    3499
1     3442
29    3163
30    3110
31    1861
Name: count, dtype: int64
DateCreditPulledYear
2013    35250
2012    19649
2007    11491
2011    11386
2008    11053
2014    10887
2006     6373
2010     5622
2009     2202
2005       24
Name: count, dtype: int64
DateCreditPulledMonth
1     11138
10    10440
11    10292
2     10219
9     10080
12     9943
7      9561
8      9122
6      8789
5      8548
3      8101
4      7704
Name: count, dtype: int64
DateCreditPulledDay
5     4048
6     4043
4     3991
7     3957
17    3939
3     3912
9     3873
15    3868
16    3855
13    3848
11    3821
12    3817
10    3803
21    3792
22    3783
26    3777
20    3770
2     3724
8     3715
14    3692
27    3685
23    3680
18    3677
28    3612
19    3589
24    3555
1     3554
25    3409
30    3173
29    3163
31    1812
Name: count, dtype: int64
LoanOriginationQuarterYear
2013    34345
2012    19553
2014    12172
2008    11552
2007    11460
2011    11228
2006     5906
2010     5652
2009     2047
2005       22
Name: count, dtype: int64
LoanOriginationQuarterMonth
10    31386
1     29678
7     27967
4     24906
Name: count, dtype: int64
LoanOriginationQuarterDay
1    113937
Name: count, dtype: int64

### Creating the LoanTenure variable

LoanTenure = ((MaturityDate_OriginalYear - LoanDateYear)*12) - (MaturityDate_OriginalMonth - LoanDateMonth)

In [7]:
df.columns

Index(['ListingCreationDate', 'CreditGrade', 'Term', 'ClosedDate',
       'BorrowerAPR', 'BorrowerRate', 'ProsperRating (numeric)',
       'ProsperRating (Alpha)', 'ListingCategory (numeric)', 'BorrowerState',
       'Occupation', 'EmploymentStatus', 'EmploymentStatusDuration',
       'IsBorrowerHomeowner', 'CurrentlyInGroup', 'DateCreditPulled',
       'CreditScoreRangeLower', 'CurrentCreditLines',
       'TotalCreditLinespast7years', 'InquiriesLast6Months', 'TotalInquiries',
       'CurrentDelinquencies', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'BankcardUtilization', 'AvailableBankcardCredit',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'DebtToIncomeRatio', 'IncomeRange', 'IncomeVerifiable',
       'StatedMonthlyIncome', 'LoanCurrentDaysDelinquent',
       'LoanMonthsSinceOrigination', 'LoanOriginalAmount',
       'LoanOriginationDate', 'LoanOriginationQuarter', 'MonthlyLoanPayment',
       'LP_CustomerPayments', 'LP_CustomerPrincipalPayments', 'LP_ServiceFees',
       'LP_CollectionFees', 'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'Investors', 'IsDefaulted',
       'LoanOriginationYear', 'LoanOriginationMonth', 'LoanOriginationDay',
       'ClosedDateYear', 'ClosedDateMonth', 'ClosedDateDay',
       'ListingCreationYear', 'ListingCreationMonth', 'ListingCreationDay',
       'DateCreditPulledYear', 'DateCreditPulledMonth', 'DateCreditPulledDay',
       'LoanOriginationQuarterYear', 'LoanOriginationQuarterMonth',
       'LoanOriginationQuarterDay'],
      dtype='object')

In [8]:
df['ClosedDateYear'].value_counts()

ClosedDateYear
2013    43583
2012    19132
2014    14854
2011    11066
2009     8197
2010     7633
2008     5703
2007     3363
2006      398
2005        8
Name: count, dtype: int64

In [9]:
df['LoanTenure'] =((df['ClosedDateYear'] - df['LoanOriginationYear'])*12) - (df['ClosedDateMonth'] - df['LoanOriginationMonth'])

df['LoanTenure'].describe()

count    113937.000000
mean          9.491140
std          14.042678
min         -27.000000
25%           0.000000
50%           0.000000
75%          18.000000
max          59.000000
Name: LoanTenure, dtype: float64

In [10]:
df.shape

(113937, 67)

##### Creating Equated Monthly Installments(EMI) Variable

**Loan Tenure - LoanTenure**

**Principal Amount - LP_CustomerPayment**

**Interest - BorrowerRate**

In [11]:
emi_cols = ['LP_CustomerPrincipalPayments', 'LP_CustomerPayments']

In [12]:
df[emi_cols].head()

   LP_CustomerPrincipalPayments  LP_CustomerPayments
0                       9425.00             11396.14
1                          0.00                 0.00
2                       3001.00              4186.63
3                       4091.09              5143.20
4                       1563.22              2819.85

 For each row in the dataset
 <!-- result_1 = p*r*(1+r)^n -->
 <!-- result_2 = (1+r)^n-1 -->
 <!-- EMI =result_1/result_2 -->

In [13]:
def cal_emi(p,r,n):
    p = p.values
    r = r.values
    n = n.values
    #create an empty arrays 
    result_1 = np.empty(0)
    result_2 = np.empty(0)
    result = np.empty(0)
    for i in range(p.shape[0]):
        #emi = p*r*(1+r)^n/((1+r)^n-1)
        result_1 = np.append(result_1, p[i]* r[i] * np.power((1+r[i]),n[i]))
        result_2 = np.append(result_2,np.power((1+r[i]),n[i] -1))
        result = np.append(result, result_1[i]/result_2[i])
    return result

In [14]:
df['EMI'] = cal_emi(df['LP_CustomerPrincipalPayments'], df['BorrowerRate'],df['LoanTenure'])

In [15]:
df['EMI'].describe()

count    113937.000000
mean        665.782287
std         873.727198
min           0.000000
25%         107.343768
50%         333.563040
75%         876.400965
max       11852.832600
Name: EMI, dtype: float64

##### Eligible Loan Amount(ELA)

* **Components of ELA:**

* **Applied Amount(A) - LoanOriginalAmount**
* **Interest(R) - BorrowerRate**
* **LoanTenure(N)- LoanTenure**
* **Income Total(I) - StatedMonthlyIncome**

In [16]:
ela_cols = ['DebtToIncomeRatio', 'IncomeRange', 'IncomeVerifiable',
       'StatedMonthlyIncome']

In [17]:
df[ela_cols].head()

   DebtToIncomeRatio     IncomeRange  IncomeVerifiable  StatedMonthlyIncome
0               0.17  $25,000-49,999              True          3083.333333
1               0.18  $50,000-74,999              True          6125.000000
2               0.06   Not displayed              True          2083.333333
3               0.15  $25,000-49,999              True          2875.000000
4               0.26       $100,000+              True          9583.333333

In [18]:
df.shape

(113937, 68)

In [19]:
df['BorrowerRate'].describe()

count    113937.000000
mean          0.192764
std           0.074818
min           0.000000
25%           0.134000
50%           0.184000
75%           0.250000
max           0.497500
Name: BorrowerRate, dtype: float64

In [20]:
# To know the number of people with verifiable income
df_veriable = df[df['IncomeVerifiable'] == True]

print(df_veriable.shape)
print(df.shape[0] - df_veriable.shape[0])

(105268, 68)
8669

* **For each row in the dataset:**

Calculate: Total Payment Due = (A + (A*r)) * n

Calculate: Max allowable amount = I * 12 * 30%

If ( Total Payment Due <= Max allowable amount)

  Then ELA = AppliedAmount
  
   Else ELA = Max allowable amount

In [21]:
df['LoanOriginalAmount'].describe()

count    113937.00000
mean       8337.01385
std        6245.80058
min        1000.00000
25%        4000.00000
50%        6500.00000
75%       12000.00000
max       35000.00000
Name: LoanOriginalAmount, dtype: float64

In [22]:
def eligible_loan(df):
    df['available_income'] = (df['StatedMonthlyIncome'] * 12 * 0.3) * df['LoanTenure']
    df['Total_loan_Amnt'] = np.round(df['LoanOriginalAmount'] + (df['LoanOriginalAmount'] 
                                                                 * df['BorrowerRate']) * df['LoanTenure'])
    ELA = np.empty(0)
    for i in range(len(df['available_income'].values)):
        if df['available_income'].iloc[i] <= 0:
            ELA = np.append(ELA, 0)
        elif df['Total_loan_Amnt'].iloc[i] <= df['available_income'].iloc[i]:
            ELA = np.append(ELA, df['Total_loan_Amnt'].iloc[i])
        else:
            ELA = np.append(ELA, df['available_income'].iloc[i])
    
    df.drop(['available_income', 'Total_loan_Amnt'], axis=1, inplace=True)
    
    return ELA

In [23]:
df['ELA'] = eligible_loan(df)

In [24]:
df['ELA'].describe()

count    113937.000000
mean      12987.043887
std       24371.638474
min           0.000000
25%           0.000000
50%           0.000000
75%       17802.000000
max      392500.000000
Name: ELA, dtype: float64

In [25]:
df['ELA'].value_counts()

ELA
0.0        67374
20520.0       65
21791.0       64
19250.0       62
13600.0       62
           ...
41980.0        1
19809.0        1
3185.0         1
92600.0        1
18978.0        1
Name: count, Length: 24286, dtype: int64

##### Prefered Return on Investment(PROI)

In [26]:
# def PROI(df):
#     # To calculate ROI
#     df['interestAmount'] = df['LoanOriginalAmount'] * df['BorrowerRate']
#     df['TotalAmount'] = df['interestAmount'] + df['LoanOriginalAmount']
#     df['ROI'] = df['interestAmount'] / df['TotalAmount']
#     # Setting PROI
#     df['PROI'] = df['ROI'].median()

#     for i in range(df.shape[0]):
#         #Check for LP_CustomerPrincipalPayment
#         if df['LP_CustomerPrincipalPayments'].iloc[i] <= 1000:
#             df['LP_CustomerPrincipalPayments'].iloc[i] = df['LP_CustomerPrincipalPayments'].iloc[i] + 0.05
#         elif (df['LP_CustomerPrincipalPayments'].iloc[i] > 2000) & (df['LP_CustomerPrincipalPayments'].iloc[i] <= 10500):
#             df['LP_CustomerPrincipalPayments'].iloc[i] = df['LP_CustomerPrincipalPayments'].iloc[i] - 0.05
#         elif (df['LP_CustomerPrincipalPayments'].iloc[i]) > 10500:
#             df['LP_CustomerPrincipalPayments'].iloc[i] = df['LP_CustomerPrincipalPayments'].iloc[i] - 0.1

#         # Check for prosper rating
#         if df['ProsperRating (Alpha)'].iloc[i] in [2,3]:
#                 df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05

#         elif df['ProsperRating (Alpha)'].iloc[i] == 6:
#                 df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
            
#         # Check for loanoriginalamount
#         if df['LoanOriginalAmount'].iloc[i] <= 2000:
#              df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
#         elif (df['LoanOriginalAmount'].iloc[i] > 19500) & (df['LoanOriginalAmount'].iloc[i] <= 25500):
#              df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05
#         elif df['LoanOriginalAmount'].iloc[i] > 25500:
#              df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.1

#         # Check for loancurrentdaydeliquent
#         if (df['LoanCurrentDaysDelinquent'].iloc[i] >= 50):
#              df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05

#         # Check for monthlypayment
#         if (df['MonthlyLoanPayment'].iloc[i] <= 90):
#             df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
#         elif (df['MonthlyLoanPayment'].iloc[i] <= 750) & (df['MonthlyLoanPayment'].iloc[i] > 360):
#             df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05

#     return df['PROI']

In [27]:
def PROI(df):
    # Calculate ROI
    df['InterestAmount'] = (df['LoanOriginalAmount']*(df['BorrowerRate']))
    df['TotalAmount'] = (df['InterestAmount'] + df['LoanOriginalAmount'])
    df['ROI'] = (df['InterestAmount'] / df['TotalAmount'])
    print(df['ROI'].describe())
    
    # Setting PROI
    df['PROI'] = df['ROI'].median()

    for i in range(df.shape[0]):
        # Check for LP_CustomerPrinciplePayment
        if df['LP_CustomerPrincipalPayments'].iloc[i] <= 1000:
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05
        elif (df['LP_CustomerPrincipalPayments'].iloc[i] > 2000) & (df['LP_CustomerPrincipalPayments'].iloc[i] <= 10500):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
        elif (df['LP_CustomerPrincipalPayments'].iloc[i] > 10500):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.1
        
        # Check for ProsperRating
        if df['ProsperRating (Alpha)'].iloc[i] in [2, 3]:
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05
        elif df['ProsperRating (Alpha)'].iloc[i] == 6:
            df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05

        # Check for LoanOriginalAmount
        if df['LoanOriginalAmount'].iloc[i] <= 2000:
            df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
        elif (df['LoanOriginalAmount'].iloc[i] > 19500) & (df['LoanOriginalAmount'].iloc[i] <= 25500):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05
        elif df['LoanOriginalAmount'].iloc[i] > 25500:
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.1

        # Check for LoanCurrentDaysDelinquent
        if (df['LoanCurrentDaysDelinquent'].iloc[i] >= 50):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05

        # Check for MonthlyLoanPayment
        if (df['MonthlyLoanPayment'].iloc[i] <= 90):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] - 0.05
        elif (df['MonthlyLoanPayment'].iloc[i] <= 750) & (df['MonthlyLoanPayment'].iloc[i] > 360):
            df['PROI'].iloc[i] = df['PROI'].iloc[i] + 0.05

    

    return df['PROI']

In [28]:
df['PROI'] = PROI(df)
df['PROI'].describe()

count    113937.000000
mean          0.158343
std           0.052204
min           0.000000
25%           0.118166
50%           0.155405
75%           0.200000
max           0.332220
Name: ROI, dtype: float64

count    113937.000000
mean          0.162498
std           0.064231
min           0.005405
25%           0.105405
50%           0.155405
75%           0.205405
max           0.355405
Name: PROI, dtype: float64

In [29]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [30]:
# Drop the date columns
df.drop(['ListingCreationDate','ClosedDate','LoanOriginationDate','LoanOriginationQuarter'], axis=1, inplace=True)

In [31]:
cat_cols = df.select_dtypes(include='object').columns
cat_cols

Index(['CreditGrade', 'ProsperRating (Alpha)', 'BorrowerState', 'Occupation',
       'EmploymentStatus', 'DateCreditPulled', 'IncomeRange'],
      dtype='object')

In [32]:
# Encode the categorical columns
encoder = LabelEncoder()

for col in cat_cols:
    df[col] = encoder.fit_transform(df[col])

In [33]:
# # Check for the boolean columns
bool_cols = df.select_dtypes(include='boolean').columns
bool_cols

Index(['IsBorrowerHomeowner', 'CurrentlyInGroup', 'IncomeVerifiable'], dtype='object')

In [34]:
for col in bool_cols:
    df[col] = df[col].astype(int)

In [35]:
df.isna().sum().sum()

np.int64(0)

#### Feature Selection Analysis

In [36]:


# Select the target variables
target_vars = ['ELA', 'EMI', 'PROI']

for target in target_vars:
    # Separate features and target variable
    X = df.drop(target, axis=1)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    y = df[target]

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    # Create a Random Forest Regressor
    rf_reg = RandomForestRegressor(random_state=42)

    # Fit the model
    rf_reg.fit(X_train, y_train)

    # Make predictions
    y_pred = rf_reg.predict(X_test)

    # Evaluate the model
    print(f"\nRegression Model For Target: {target}")
    print(f'Mean Squared Error: {mean_squared_error(y_test, y_pred)}')
    print(f'Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}')
    print(f'R2 Score: {r2_score(y_test, y_pred)}')

    # Get feature importances
    feature_importances = pd.DataFrame({'Feature Name': X.columns, 'importance': rf_reg.feature_importances_})
    feature_importances.sort_values(by='importance', ascending=False, inplace=True)
    print(f"\nTop 10 Important Features for {target}:")
    print(feature_importances.head(10))

Regression Model For Target: ELA
Mean Squared Error: 954714.077074538
Mean Absolute Error: 186.02913691915484
R2 Score: 0.998389491758454

Top 10 Important Features for ELA:
             Feature Name  importance
62             LoanTenure    0.541062
64         InterestAmount    0.398666
30    StatedMonthlyIncome    0.039046
65            TotalAmount    0.016840
34     MonthlyLoanPayment    0.001076
63                    EMI    0.000689
35    LP_CustomerPayments    0.000407
27      DebtToIncomeRatio    0.000136
2             BorrowerAPR    0.000122
39  LP_GrossPrincipalLoss    0.000113

Regression Model For Target: EMI
Mean Squared Error: 1030.2057070680978
Mean Absolute Error: 5.777374179146399
R2 Score: 0.9986228259685006

Top 10 Important Features for EMI:
                    Feature Name  importance
35           LP_CustomerPayments    0.740089
64                InterestAmount    0.098098
36  LP_CustomerPrincipalPayments    0.064637
66                           ROI    0.035774
3                   BorrowerRate    0.034697
2                    BorrowerAPR    0.016522
39         LP_GrossPrincipalLoss    0.003467
37                LP_ServiceFees    0.002917
33            LoanOriginalAmount    0.000665
65                   TotalAmount    0.000550

Regression Model For Target: PROI
Mean Squared Error: 1.2319641916798268e-06
Mean Absolute Error: 4.2697911186255044e-05
R2 Score: 0.9997053837976233

Top 10 Important Features for PROI:
                    Feature Name  importance
36  LP_CustomerPrincipalPayments    0.606013
34            MonthlyLoanPayment    0.274800
31     LoanCurrentDaysDelinquent    0.092546
33            LoanOriginalAmount    0.024746
66                   TotalAmount    0.001314
46                   IsDefaulted    0.000162
39         LP_GrossPrincipalLoss    0.000130
13              DateCreditPulled    0.000062
40           LP_NetPrincipalLoss    0.000032
35           LP_CustomerPayments    0.000022

In [37]:
x = feature_importances
x

                    Feature Name    importance
36  LP_CustomerPrincipalPayments  6.060131e-01
34            MonthlyLoanPayment  2.747995e-01
31     LoanCurrentDaysDelinquent  9.254591e-02
33            LoanOriginalAmount  2.474620e-02
66                   TotalAmount  1.313780e-03
..                           ...           ...
43               Recommendations  2.555675e-17
22     PublicRecordsLast12Months  1.127459e-17
29              IncomeVerifiable  8.856217e-18
61     LoanOriginationQuarterDay  0.000000e+00
12              CurrentlyInGroup -3.558253e-18

[68 rows x 2 columns]

##### Model Building

##### Feature Selection

In [42]:


# Select the target variables
target_vars = ['ELA', 'EMI', 'PROI']
all_selected_feat = []

for target in target_vars:
    # Separate features and target variable
    X = df.drop(target, axis=1)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    y = df[target]

    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

    # Create a Random Forest Regressor
    rf_reg = RandomForestRegressor(random_state=42)

    # Fit the model
    rf_reg.fit(X_train, y_train)

    # Make predictions
    y_pred = rf_reg.predict(X_test)

    # Evaluate the model
    print(f"\nRegression Model For Target: {target}")
    print(f'Mean Squared Error: {mean_squared_error(y_test, y_pred)}')
    print(f'Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}')
    print(f'R2 Score: {r2_score(y_test, y_pred)}')

    # Get feature importances
    feature_importances = pd.DataFrame({'Feature Name': X.columns, 'importance': rf_reg.feature_importances_})
    feature_importances.sort_values(by='importance', ascending=False, inplace=True)

    # Select features based on importance 
    selected_features = feature_importances['Feature Name'].head(10).tolist()
    
    # Store selected features 
    all_selected_feat.extend(selected_features)

    print(f"\nTop 10 Important Features for {target}:")
    print(feature_importances.head(10))

Regression Model For Target: ELA
Mean Squared Error: 954714.077074538
Mean Absolute Error: 186.02913691915484
R2 Score: 0.998389491758454

Top 10 Important Features for ELA:
             Feature Name  importance
62             LoanTenure    0.541062
64         InterestAmount    0.398666
30    StatedMonthlyIncome    0.039046
65            TotalAmount    0.016840
34     MonthlyLoanPayment    0.001076
63                    EMI    0.000689
35    LP_CustomerPayments    0.000407
27      DebtToIncomeRatio    0.000136
2             BorrowerAPR    0.000122
39  LP_GrossPrincipalLoss    0.000113

Regression Model For Target: EMI
Mean Squared Error: 1030.2057070680978
Mean Absolute Error: 5.777374179146399
R2 Score: 0.9986228259685006

Top 10 Important Features for EMI:
                    Feature Name  importance
35           LP_CustomerPayments    0.740089
64                InterestAmount    0.098098
36  LP_CustomerPrincipalPayments    0.064637
66                           ROI    0.035774
3                   BorrowerRate    0.034697
2                    BorrowerAPR    0.016522
39         LP_GrossPrincipalLoss    0.003467
37                LP_ServiceFees    0.002917
33            LoanOriginalAmount    0.000665
65                   TotalAmount    0.000550

Regression Model For Target: PROI
Mean Squared Error: 1.2319641916798268e-06
Mean Absolute Error: 4.2697911186255044e-05
R2 Score: 0.9997053837976233

Top 10 Important Features for PROI:
                    Feature Name  importance
36  LP_CustomerPrincipalPayments    0.606013
34            MonthlyLoanPayment    0.274800
31     LoanCurrentDaysDelinquent    0.092546
33            LoanOriginalAmount    0.024746
66                   TotalAmount    0.001314
46                   IsDefaulted    0.000162
39         LP_GrossPrincipalLoss    0.000130
13              DateCreditPulled    0.000062
40           LP_NetPrincipalLoss    0.000032
35           LP_CustomerPayments    0.000022

##### Linear Regression

In [43]:
# Create a list for the target variables
target_vars = ['ELA', 'EMI', 'PROI']  # Corrected variable name to plural 'vars'
X = df[all_selected_feat]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y = df[target_vars]

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Create a multioutput regressor with Linear regression
model = MultiOutputRegressor(LinearRegression())

# Fit the model
model.fit(X_train, y_train)

# Make prediction with X_test
y_pred_r = model.predict(X_test)

# Calculate and print regression metrics with loop
for i, target in enumerate(target_vars):
  print(f"\nRegression Model For Target: {target}")
  print(f"Mean Square Error: {mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Root Mean Square Error: {root_mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Mean Absolute Error: {mean_absolute_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"R2 Score: {r2_score(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")

Regression Model For Target: ELA
Mean Square Error: 125262373.97
Root Mean Square Error: 11192.07
Mean Absolute Error: 6467.10
R2 Score: 0.79

Regression Model For Target: EMI
Mean Square Error: 0.00
Root Mean Square Error: 0.00
Mean Absolute Error: 0.00
R2 Score: 1.00

Regression Model For Target: PROI
Mean Square Error: 0.00
Root Mean Square Error: 0.03
Mean Absolute Error: 0.03
R2 Score: 0.76

##### LASSO L1

In [45]:
# Create a list for the target variables
target_vars = ['ELA', 'EMI', 'PROI']  # Corrected variable name to plural 'vars'
X = df[all_selected_feat]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y = df[target_vars]

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Create a multioutput regressor with Linear regression
model = MultiOutputRegressor(Lasso())

# Fit the model
model.fit(X_train, y_train)

# Make prediction with X_test
y_pred_r = model.predict(X_test)

# Calculate and print regression metrics with loop
for i, target in enumerate(target_vars):
  print(f"\nLASSO Regression Model For Target: {target}")
  print(f"Mean Square Error: {mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Root Mean Square Error: {root_mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Mean Absolute Error: {mean_absolute_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"R2 Score: {r2_score(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")

LASSO Regression Model For Target: ELA
Mean Square Error: 125295102.02
Root Mean Square Error: 11193.53
Mean Absolute Error: 6461.71
R2 Score: 0.79

LASSO Regression Model For Target: EMI
Mean Square Error: 0.97
Root Mean Square Error: 0.99
Mean Absolute Error: 0.69
R2 Score: 1.00

LASSO Regression Model For Target: PROI
Mean Square Error: 0.00
Root Mean Square Error: 0.06
Mean Absolute Error: 0.06
R2 Score: -0.00

##### Ridge L2

In [46]:
# Create a list for the target variables
target_vars = ['ELA', 'EMI', 'PROI']  # Corrected variable name to plural 'vars'
X = df[all_selected_feat]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y = df[target_vars]

# Split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Create a multioutput regressor with Linear regression
model = MultiOutputRegressor(Ridge())

# Fit the model
model.fit(X_train, y_train)

# Make prediction with X_test
y_pred_r = model.predict(X_test)

# Calculate and print regression metrics with loop
for i, target in enumerate(target_vars):
  print(f"\nRIDGE Regression Model For Target: {target}")
  print(f"Mean Square Error: {mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Root Mean Square Error: {root_mean_squared_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"Mean Absolute Error: {mean_absolute_error(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")
  print(f"R2 Score: {r2_score(y_test.iloc[:, i], y_pred_r[:, i]):.2f}")

RIDGE Regression Model For Target: ELA
Mean Square Error: 125284838.90
Root Mean Square Error: 11193.07
Mean Absolute Error: 6464.65
R2 Score: 0.79

RIDGE Regression Model For Target: EMI
Mean Square Error: 0.00
Root Mean Square Error: 0.03
Mean Absolute Error: 0.02
R2 Score: 1.00

RIDGE Regression Model For Target: PROI
Mean Square Error: 0.00
Root Mean Square Error: 0.03
Mean Absolute Error: 0.03
R2 Score: 0.76